# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
workspace 'mobile-app-pembayaran-qris'

def shared_pod
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile-app-pembayaran-qris
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'Verge'
end

target 'mobile-app-pembayaran-qris' do
  shared_pod
  
  target 'mobile-app-pembayaran-qris-tests' do
    inherit! :search_paths
  end
end

target 'core' do
  project '../core/core'

end
